name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  page_build:
  release:
    types:
      - created
      - edited
      - prereleased
      - released

env:
  # Build a release build
  BUILD_TYPE: Release
  # MSVC installation directory 
  VCINSTALLDIR: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/
  # The Qt installation dir for CMake
  Qt5_DIR: Qt\5.15.2\msvc2017\lib\cmake\Qt5\
  # The Qt root dir
  QTDIR: Qt\5.15.2\msvc2017\

jobs:
  windows:
    timeout-minutes: 15
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_msvc2019'
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Compile
      run: cmake --build ${{github.workspace}}/build -G "Visual Studio 16 2019" -A Win32 --config ${{env.BUILD_TYPE}}

    - name: Package
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release --target package

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/ConductorLogFoo*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}